-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 15, 2021 at 10:25 AM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.4.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `email_list`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_login`
--

CREATE TABLE `admin_login` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `admin_login`
--

INSERT INTO `admin_login` (`id`, `username`, `email`, `password`) VALUES
(2, 'officialnextgenpixel', 'rajkamalgautam2001@gmail.com', '$2y$10$aI4g02olMHOieD3TpFMf2eW5FOfuaKAAzs/As2EzmEuBlJTlCWPSO');

-- --------------------------------------------------------

--
-- Table structure for table `email_list`
--

CREATE TABLE `email_list` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `htmlfile` varchar(255) NOT NULL,
  `UserWhocreated` varchar(255) NOT NULL,
  `createdByWhom` varchar(255) NOT NULL,
  `send` int(11) NOT NULL,
  `open` int(11) NOT NULL,
  `createdAt` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `email_list`
--

INSERT INTO `email_list` (`id`, `email`, `content`, `htmlfile`, `UserWhocreated`, `createdByWhom`, `send`, `open`, `createdAt`) VALUES
(11, 'loremipsum@gmail.com', '<p><strong>Email marketing</strong>&nbsp;is the act of sending a commercial message, typically to a group of people, using&nbsp;<strong>email</strong>. In its broadest sense, every&nbsp;<strong>email</strong>&nbsp;sent to a potential or current customer could be considered&nbsp;<strong>email marketing</strong>. It involves using&nbsp;<strong>email</strong>&nbsp;to send advertisements, request business, or solicit sales or donations</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/emailmarketingguide.png\" style=\"height:156px; width:300px\" /></p>\r\n', 'rajkamal_gottam-gsgs.html', 'Rajkamal_Gottam', '4', 0, 0, '2021-06-15 11:37:08'),
(12, 'testingpixel9943@gmail.com', '<p><strong>Email marketing</strong>&nbsp;is the act of sending a commercial message, typically to a group of people, using&nbsp;<strong>email</strong>. In its broadest sense, every&nbsp;<strong>email</strong>&nbsp;sent to a potential or current customer could be considered&nbsp;<strong>email marketing</strong>. It involves using&nbsp;<strong>email</strong>&nbsp;to send advertisements, request business, or solicit sales or donations</p>\r\n\r\n<p><img alt=\"\" src=\"ckeditor/uploads/emailmarketingguide.png\" style=\"height:156px; width:300px\" /></p>\r\n', 'rajkamal_gottam-gsgs.html', 'Rajkamal_Gottam', '4', 0, 0, '2021-06-15 11:37:08'),
(13, 'rajkamalgautam2001@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(15, 'official.nextgenpixel@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(16, 'chandreshchauhan2001@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(19, 'arnavmontysharma@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(20, 'arryantelge55@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(21, 'aunmahdi30@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(22, 'bhambhani123456@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(23, 'chandrakamalgautam@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(24, 'darshanbambhaniya1873@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(25, 'ghrutisingh26@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(26, 'idrisi.rehan@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(27, 'jainaman337@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(28, 'jaiswaljuhi150203@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(29, 'pawaranish24@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(30, 'rishabwahi77@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(31, 'sathiadak003@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(32, 'shkmoin786@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(33, 'ujwallodaya786.ul@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(34, 'mvp104.vm@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(35, 'fawkinck@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(36, 'premgujar6460@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(37, 'jainniraj40@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(38, 'noelpinto47@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(39, 'shyamkumaryadav2003@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(40, 'sspanda1700@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(41, 'raunakagrahari15@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(42, 'shreyasmohite786@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(43, 'nagularamya9@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(44, 'sanjeevpandit195@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(45, 'shikha42001@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(46, 'hjhitesh9680162137@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(47, 'pradev2002@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(48, 'hjoshi30042001@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(49, 'gudadreddy1967@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(50, 'rohitsalve98@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(51, 'simranyadav0610@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(52, 'palaash.sarkar@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(53, 'padmakamble2000@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(54, 'singhashwini954@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(55, 'tejaspophale01@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(56, 'soumyaspillai2001@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(57, 'motenamita@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45');
INSERT INTO `email_list` (`id`, `email`, `content`, `htmlfile`, `UserWhocreated`, `createdByWhom`, `send`, `open`, `createdAt`) VALUES
(58, 'sadiyamhate98@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(59, 'btiwari01412@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(60, 'priyauy2003@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(61, 'siddhesh.s.pansare@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(62, 'sshalinisi10@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(63, 'poorvashukla315@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(64, 'anuragk2764@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(65, 'gauravgupta14376@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(66, 'charitaranadive29@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(67, 'hrithikunawane@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(68, 'frolikpicxel@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(69, 'shahabtemkar@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(70, 'Arshadbamne@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(71, 'yug.narang10@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(72, 'chiraayupm2@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(73, 'rohitbhosale11051@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(74, 'mp573218@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(75, 'boneyash12@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(76, 'kirtankotian5@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(77, 'aryanbhosale2411@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(78, 'pixelgenmarketing@gmail.com', '<hr />\r\n<div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>\r\n\r\n<hr />\r\n<p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>\r\n\r\n<p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>\r\n\r\n<p>Thanks &amp; Regards,<br />\r\n<ins>Nextgenpixel</ins></p>\r\n\r\n<p>&nbsp;</p>\r\n', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-07 11:39:45'),
(80, 'ashiwinikolhi@gmail.com', '<p>hi</p>\r\n', '', 'darshan', '9', 0, 0, '2021-06-22 09:42:49'),
(82, 'testingpixel9943@gmail.com', '<hr /> <div style=\"background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;\">*Get a Free 7day Trial of Our E-mail Marketing Service*</div>  <hr /> <p><img alt=\"\" src=\"https://marshall-rk.github.io/nextgenpixel/design-images/post1.jpg\" style=\"border-style:solid; border-width:1px; float:right; height:300px; margin:1px; width:300px\" /></p>  <p>We believe we&rsquo;ve built a quality, easy-to-use, secure Email Marketing web app that will not only make your sending Emails more Efficient but will also highlight your brand and add professionalism to it. We at Nextgenpixel focus on creating effective and efficient strategies for Email marketing by creating detailed and value-adding content because the goal is not just reaching your potential client&#39;s inbox but their engagement. Send the right messages on the right channels by creating your own custom email, social ads, landing pages, postcards, and more.</p>  <p>Thanks &amp; Regards,<br /> <ins>Nextgenpixel</ins></p>  <p>&nbsp;</p>', 'nextgenpixel-pixel.html', 'Nextgenpixel', '5', 0, 0, '2021-07-08 23:20:31'),
(95, 'rajkamalgautam2001@gmail.com', '<h3><a href=\"https://www.justdial.com/Mumbai/Frolik-Picxel-Borivali-West/022PXX22-XX22-161118125556-U7U4_BZDET\">Frolik Picxel, Borivali West - Photographers in Mumbai - Justdial</a></h3>\r\n\r\n<h3><a href=\"https://www.justdial.com/Mumbai/Frolik-Picxel-Borivali-West/022PXX22-XX22-161118125556-U7U4_BZDET\"><cite>https://www.justdial.com&nbsp;&rsaquo; Mumbai &rsaquo; Frolik-Picxel-Bor...</cite></a></h3>\r\n\r\n<h3><em>Frolik Picxel</em>&nbsp;in Borivali West, Mumbai is one of the leading businesses in the Photographers with 21 photos. Rated 3.8 based on 18 Ratings and Reviews.</h3>\r\n', '', 'realck', '2', 0, 0, '2021-07-14 12:27:52'),
(96, 'official.nextgenpixel@gmail.com', '<h3><a href=\"https://www.justdial.com/Mumbai/Frolik-Picxel-Borivali-West/022PXX22-XX22-161118125556-U7U4_BZDET\">Frolik Picxel, Borivali West - Photographers in Mumbai - Justdial</a></h3>\r\n\r\n<h3><a href=\"https://www.justdial.com/Mumbai/Frolik-Picxel-Borivali-West/022PXX22-XX22-161118125556-U7U4_BZDET\"><cite>https://www.justdial.com&nbsp;&rsaquo; Mumbai &rsaquo; Frolik-Picxel-Bor...</cite></a></h3>\r\n\r\n<h3><em>Frolik Picxel</em>&nbsp;in Borivali West, Mumbai is one of the leading businesses in the Photographers with 21 photos. Rated 3.8 based on 18 Ratings and Reviews.</h3>\r\n', '', 'realck', '2', 0, 0, '2021-07-14 12:27:52'),
(97, 'pixelgenmarketing@gmail.com', '<h3><a href=\"https://www.justdial.com/Mumbai/Frolik-Picxel-Borivali-West/022PXX22-XX22-161118125556-U7U4_BZDET\">Frolik Picxel, Borivali West - Photographers in Mumbai - Justdial</a></h3>\r\n\r\n<h3><a href=\"https://www.justdial.com/Mumbai/Frolik-Picxel-Borivali-West/022PXX22-XX22-161118125556-U7U4_BZDET\"><cite>https://www.justdial.com&nbsp;&rsaquo; Mumbai &rsaquo; Frolik-Picxel-Bor...</cite></a></h3>\r\n\r\n<h3><em>Frolik Picxel</em>&nbsp;in Borivali West, Mumbai is one of the leading businesses in the Photographers with 21 photos. Rated 3.8 based on 18 Ratings and Reviews.</h3>\r\n', '', 'realck', '2', 0, 0, '2021-07-14 12:27:52');

-- --------------------------------------------------------

--
-- Table structure for table `pixelemail`
--

CREATE TABLE `pixelemail` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `accstatus` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `mobile_number` varchar(255) NOT NULL,
  `AadharCard_number` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `pixelemail`
--

INSERT INTO `pixelemail` (`id`, `username`, `accstatus`, `email`, `mobile_number`, `AadharCard_number`, `image`, `password`, `date`) VALUES
(2, 'realck', 'Expire', 'chandrakamalgautam@gmail.com', '7276323147', '2147483647', 'chandrakamalgautam@gmail.com1623643661low2.jpg', '$2y$10$kfBgOe3wbdn4p6FFbcQnQ.O2nIZC.JcQI4glC3H0wnXkh9Kxjmyze', '2021-06-14 22:20:41'),
(4, 'Rajkamal_Gottam', 'Expire', 'rajkamalgautam2001@gmail.com', '7066301198', '514254145632', 'rajkamalgautam2001@gmail.com1623749598262943.jpg', '$2y$10$vSZz2EvGz1DahiS.wRqGGemo/wMlQVLzeCzPnUmhRWbQTFmhS1r0u', '2021-06-15 15:03:18'),
(5, 'Nextgenpixel', 'Expire', 'official.nextgenpixel@gmail.com', '9503874589', '511254785954', 'official.nextgenpixel@gmail.com1623726128aadhar.jpeg', '$2y$10$mt5mg0rnWPXClkJ5mMDymeVY.2qJXT8LJQVuQv7J61cOpwa1PxlPq', '2021-06-15 20:32:08'),
(11, 'shashigautam', 'Active', 'shashi@gmail.com', '7276323179', '125412555687', 'shashi@gmail.com1625558306IMG-20210702-WA0023.jpg', '$2y$10$8go9DDNuzRMEpy0D6EzNOevm8CUNShEK2gInbp3kUKPa3MeSbVm0i', '2021-07-06 13:28:26');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_login`
--
ALTER TABLE `admin_login`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `email_list`
--
ALTER TABLE `email_list`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `pixelemail`
--
ALTER TABLE `pixelemail`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_login`
--
ALTER TABLE `admin_login`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `email_list`
--
ALTER TABLE `email_list`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=98;

--
-- AUTO_INCREMENT for table `pixelemail`
--
ALTER TABLE `pixelemail`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
